/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"


/********************   ProgramDefs    ********************/
Program make_ProgramDefs(ListDef p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ProgramDefs!\n");
        exit(1);
    }
    tmp->kind = is_ProgramDefs;
    tmp->u.programdefs_.listdef_ = p1;
    return tmp;
}/********************   ListDef    ********************/
ListDef make_ListDef(Def p1, ListDef p2)
{
    ListDef tmp = (ListDef) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListDef!\n");
        exit(1);
    }
    tmp->def_ = p1;
    tmp->listdef_ = p2;
    return tmp;
}/********************   DefFun    ********************/
Def make_DefFun(Id p1, ListArg p2, Type p3, ListStm p4)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating DefFun!\n");
        exit(1);
    }
    tmp->kind = is_DefFun;
    tmp->u.deffun_.id_ = p1;
    tmp->u.deffun_.listarg_ = p2;
    tmp->u.deffun_.type_ = p3;
    tmp->u.deffun_.liststm_ = p4;
    return tmp;
}
/********************   DefFunExposed    ********************/
Def make_DefFunExposed(Id p1, ListArg p2, Type p3, ListStm p4)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating DefFunExposed!\n");
        exit(1);
    }
    tmp->kind = is_DefFunExposed;
    tmp->u.deffunexposed_.id_ = p1;
    tmp->u.deffunexposed_.listarg_ = p2;
    tmp->u.deffunexposed_.type_ = p3;
    tmp->u.deffunexposed_.liststm_ = p4;
    return tmp;
}
/********************   DefTypedef    ********************/
Def make_DefTypedef(Ident p1, Type p2, Type p3)
{
    Def tmp = (Def) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating DefTypedef!\n");
        exit(1);
    }
    tmp->kind = is_DefTypedef;
    tmp->u.deftypedef_.ident_ = p1;
    tmp->u.deftypedef_.type_1 = p2;
    tmp->u.deftypedef_.type_2 = p3;
    return tmp;
}/********************   ListArg    ********************/
ListArg make_ListArg(Arg p1, ListArg p2)
{
    ListArg tmp = (ListArg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListArg!\n");
        exit(1);
    }
    tmp->arg_ = p1;
    tmp->listarg_ = p2;
    return tmp;
}/********************   ListStm    ********************/
ListStm make_ListStm(Stm p1, ListStm p2)
{
    ListStm tmp = (ListStm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListStm!\n");
        exit(1);
    }
    tmp->stm_ = p1;
    tmp->liststm_ = p2;
    return tmp;
}/********************   ArgDecl    ********************/
Arg make_ArgDecl(Id p1, Type p2)
{
    Arg tmp = (Arg) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ArgDecl!\n");
        exit(1);
    }
    tmp->kind = is_ArgDecl;
    tmp->u.argdecl_.id_ = p1;
    tmp->u.argdecl_.type_ = p2;
    return tmp;
}/********************   StmInit    ********************/
Stm make_StmInit(IdMaybeTyped p1, Exp p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmInit!\n");
        exit(1);
    }
    tmp->kind = is_StmInit;
    tmp->u.stminit_.idmaybetyped_ = p1;
    tmp->u.stminit_.exp_ = p2;
    return tmp;
}
/********************   StmSplit    ********************/
Stm make_StmSplit(IdMaybeTyped p1, IdMaybeTyped p2, Exp p3)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmSplit!\n");
        exit(1);
    }
    tmp->kind = is_StmSplit;
    tmp->u.stmsplit_.idmaybetyped_1 = p1;
    tmp->u.stmsplit_.idmaybetyped_2 = p2;
    tmp->u.stmsplit_.exp_ = p3;
    return tmp;
}
/********************   StmIfElse    ********************/
Stm make_StmIfElse(IfCond p1, ListStm p2, Else p3)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmIfElse!\n");
        exit(1);
    }
    tmp->kind = is_StmIfElse;
    tmp->u.stmifelse_.ifcond_ = p1;
    tmp->u.stmifelse_.liststm_ = p2;
    tmp->u.stmifelse_.else_ = p3;
    return tmp;
}
/********************   StmSwitch    ********************/
Stm make_StmSwitch(Exp p1, ListSwitchCase p2)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmSwitch!\n");
        exit(1);
    }
    tmp->kind = is_StmSwitch;
    tmp->u.stmswitch_.exp_ = p1;
    tmp->u.stmswitch_.listswitchcase_ = p2;
    return tmp;
}
/********************   StmReturn    ********************/
Stm make_StmReturn(Exp p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmReturn!\n");
        exit(1);
    }
    tmp->kind = is_StmReturn;
    tmp->u.stmreturn_.exp_ = p1;
    return tmp;
}
/********************   StmAssert    ********************/
Stm make_StmAssert(Assertion p1)
{
    Stm tmp = (Stm) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating StmAssert!\n");
        exit(1);
    }
    tmp->kind = is_StmAssert;
    tmp->u.stmassert_.assertion_ = p1;
    return tmp;
}/********************   IdMaybeTypedNotTyped    ********************/
IdMaybeTyped make_IdMaybeTypedNotTyped(Id p1)
{
    IdMaybeTyped tmp = (IdMaybeTyped) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IdMaybeTypedNotTyped!\n");
        exit(1);
    }
    tmp->kind = is_IdMaybeTypedNotTyped;
    tmp->u.idmaybetypednottyped_.id_ = p1;
    return tmp;
}
/********************   IdMaybeTypedTyped    ********************/
IdMaybeTyped make_IdMaybeTypedTyped(Id p1, Type p2)
{
    IdMaybeTyped tmp = (IdMaybeTyped) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IdMaybeTypedTyped!\n");
        exit(1);
    }
    tmp->kind = is_IdMaybeTypedTyped;
    tmp->u.idmaybetypedtyped_.id_ = p1;
    tmp->u.idmaybetypedtyped_.type_ = p2;
    return tmp;
}/********************   IfCondCase    ********************/
IfCond make_IfCondCase(IdMaybeTyped p1, Case p2, Exp p3)
{
    IfCond tmp = (IfCond) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IfCondCase!\n");
        exit(1);
    }
    tmp->kind = is_IfCondCase;
    tmp->u.ifcondcase_.idmaybetyped_ = p1;
    tmp->u.ifcondcase_.case_ = p2;
    tmp->u.ifcondcase_.exp_ = p3;
    return tmp;
}
/********************   IfCondBool    ********************/
IfCond make_IfCondBool(Exp p1)
{
    IfCond tmp = (IfCond) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IfCondBool!\n");
        exit(1);
    }
    tmp->kind = is_IfCondBool;
    tmp->u.ifcondbool_.exp_ = p1;
    return tmp;
}
/********************   IfCondUnfold    ********************/
IfCond make_IfCondUnfold(IdMaybeTyped p1, IdMaybeTyped p2, Exp p3)
{
    IfCond tmp = (IfCond) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating IfCondUnfold!\n");
        exit(1);
    }
    tmp->kind = is_IfCondUnfold;
    tmp->u.ifcondunfold_.idmaybetyped_1 = p1;
    tmp->u.ifcondunfold_.idmaybetyped_2 = p2;
    tmp->u.ifcondunfold_.exp_ = p3;
    return tmp;
}/********************   SwitchCaseDefault    ********************/
SwitchCase make_SwitchCaseDefault(IdMaybeTyped p1, Case p2, ListStm p3)
{
    SwitchCase tmp = (SwitchCase) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating SwitchCaseDefault!\n");
        exit(1);
    }
    tmp->kind = is_SwitchCaseDefault;
    tmp->u.switchcasedefault_.idmaybetyped_ = p1;
    tmp->u.switchcasedefault_.case_ = p2;
    tmp->u.switchcasedefault_.liststm_ = p3;
    return tmp;
}/********************   ListSwitchCase    ********************/
ListSwitchCase make_ListSwitchCase(SwitchCase p1, ListSwitchCase p2)
{
    ListSwitchCase tmp = (ListSwitchCase) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListSwitchCase!\n");
        exit(1);
    }
    tmp->switchcase_ = p1;
    tmp->listswitchcase_ = p2;
    return tmp;
}/********************   ElseNone    ********************/
Else make_ElseNone()
{
    Else tmp = (Else) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ElseNone!\n");
        exit(1);
    }
    tmp->kind = is_ElseNone;
    return tmp;
}
/********************   ElseStms    ********************/
Else make_ElseStms(ListStm p1)
{
    Else tmp = (Else) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ElseStms!\n");
        exit(1);
    }
    tmp->kind = is_ElseStms;
    tmp->u.elsestms_.liststm_ = p1;
    return tmp;
}/********************   Case_inl    ********************/
Case make_Case_inl()
{
    Case tmp = (Case) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Case_inl!\n");
        exit(1);
    }
    tmp->kind = is_Case_inl;
    return tmp;
}
/********************   Case_inr    ********************/
Case make_Case_inr()
{
    Case tmp = (Case) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Case_inr!\n");
        exit(1);
    }
    tmp->kind = is_Case_inr;
    return tmp;
}/********************   ExpInt    ********************/
Exp make_ExpInt(Integer p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpInt!\n");
        exit(1);
    }
    tmp->kind = is_ExpInt;
    tmp->u.expint_.integer_ = p1;
    return tmp;
}
/********************   ExpDouble    ********************/
Exp make_ExpDouble(Double p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpDouble!\n");
        exit(1);
    }
    tmp->kind = is_ExpDouble;
    tmp->u.expdouble_.double_ = p1;
    return tmp;
}
/********************   ExpUnit    ********************/
Exp make_ExpUnit()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpUnit!\n");
        exit(1);
    }
    tmp->kind = is_ExpUnit;
    return tmp;
}
/********************   ExpTrue    ********************/
Exp make_ExpTrue()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpTrue!\n");
        exit(1);
    }
    tmp->kind = is_ExpTrue;
    return tmp;
}
/********************   ExpFalse    ********************/
Exp make_ExpFalse()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpFalse!\n");
        exit(1);
    }
    tmp->kind = is_ExpFalse;
    return tmp;
}
/********************   ExpOption    ********************/
Exp make_ExpOption(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpOption!\n");
        exit(1);
    }
    tmp->kind = is_ExpOption;
    tmp->u.expoption_.exp_ = p1;
    return tmp;
}
/********************   ExpNothing    ********************/
Exp make_ExpNothing()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpNothing!\n");
        exit(1);
    }
    tmp->kind = is_ExpNothing;
    return tmp;
}
/********************   ExpId    ********************/
Exp make_ExpId(Id p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpId!\n");
        exit(1);
    }
    tmp->kind = is_ExpId;
    tmp->u.expid_.id_ = p1;
    return tmp;
}
/********************   ExpPair    ********************/
Exp make_ExpPair(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpPair!\n");
        exit(1);
    }
    tmp->kind = is_ExpPair;
    tmp->u.exppair_.exp_1 = p1;
    tmp->u.exppair_.exp_2 = p2;
    return tmp;
}
/********************   ExpSum    ********************/
Exp make_ExpSum(Ident p1, Case p2, Exp p3)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpSum!\n");
        exit(1);
    }
    tmp->kind = is_ExpSum;
    tmp->u.expsum_.ident_ = p1;
    tmp->u.expsum_.case_ = p2;
    tmp->u.expsum_.exp_ = p3;
    return tmp;
}
/********************   ExpList    ********************/
Exp make_ExpList(ListExp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpList!\n");
        exit(1);
    }
    tmp->kind = is_ExpList;
    tmp->u.explist_.listexp_ = p1;
    return tmp;
}
/********************   ExpRef    ********************/
Exp make_ExpRef(Type p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpRef!\n");
        exit(1);
    }
    tmp->kind = is_ExpRef;
    tmp->u.expref_.type_ = p1;
    return tmp;
}
/********************   ExpApp    ********************/
Exp make_ExpApp(Id p1, ListExp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpApp!\n");
        exit(1);
    }
    tmp->kind = is_ExpApp;
    tmp->u.expapp_.id_ = p1;
    tmp->u.expapp_.listexp_ = p2;
    return tmp;
}
/********************   ExpNoising    ********************/
Exp make_ExpNoising(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpNoising!\n");
        exit(1);
    }
    tmp->kind = is_ExpNoising;
    tmp->u.expnoising_.exp_ = p1;
    return tmp;
}
/********************   ExpNegative    ********************/
Exp make_ExpNegative(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpNegative!\n");
        exit(1);
    }
    tmp->kind = is_ExpNegative;
    tmp->u.expnegative_.exp_ = p1;
    return tmp;
}
/********************   ExpNot    ********************/
Exp make_ExpNot(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpNot!\n");
        exit(1);
    }
    tmp->kind = is_ExpNot;
    tmp->u.expnot_.exp_ = p1;
    return tmp;
}
/********************   ExpTimes    ********************/
Exp make_ExpTimes(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpTimes!\n");
        exit(1);
    }
    tmp->kind = is_ExpTimes;
    tmp->u.exptimes_.exp_1 = p1;
    tmp->u.exptimes_.exp_2 = p2;
    return tmp;
}
/********************   ExpDiv    ********************/
Exp make_ExpDiv(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpDiv!\n");
        exit(1);
    }
    tmp->kind = is_ExpDiv;
    tmp->u.expdiv_.exp_1 = p1;
    tmp->u.expdiv_.exp_2 = p2;
    return tmp;
}
/********************   ExpPlus    ********************/
Exp make_ExpPlus(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpPlus!\n");
        exit(1);
    }
    tmp->kind = is_ExpPlus;
    tmp->u.expplus_.exp_1 = p1;
    tmp->u.expplus_.exp_2 = p2;
    return tmp;
}
/********************   ExpMinus    ********************/
Exp make_ExpMinus(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpMinus!\n");
        exit(1);
    }
    tmp->kind = is_ExpMinus;
    tmp->u.expminus_.exp_1 = p1;
    tmp->u.expminus_.exp_2 = p2;
    return tmp;
}
/********************   ExpLt    ********************/
Exp make_ExpLt(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpLt!\n");
        exit(1);
    }
    tmp->kind = is_ExpLt;
    tmp->u.explt_.exp_1 = p1;
    tmp->u.explt_.exp_2 = p2;
    return tmp;
}
/********************   ExpGt    ********************/
Exp make_ExpGt(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpGt!\n");
        exit(1);
    }
    tmp->kind = is_ExpGt;
    tmp->u.expgt_.exp_1 = p1;
    tmp->u.expgt_.exp_2 = p2;
    return tmp;
}
/********************   ExpLtEq    ********************/
Exp make_ExpLtEq(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpLtEq!\n");
        exit(1);
    }
    tmp->kind = is_ExpLtEq;
    tmp->u.explteq_.exp_1 = p1;
    tmp->u.explteq_.exp_2 = p2;
    return tmp;
}
/********************   ExpGtEq    ********************/
Exp make_ExpGtEq(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpGtEq!\n");
        exit(1);
    }
    tmp->kind = is_ExpGtEq;
    tmp->u.expgteq_.exp_1 = p1;
    tmp->u.expgteq_.exp_2 = p2;
    return tmp;
}
/********************   ExpEq    ********************/
Exp make_ExpEq(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpEq!\n");
        exit(1);
    }
    tmp->kind = is_ExpEq;
    tmp->u.expeq_.exp_1 = p1;
    tmp->u.expeq_.exp_2 = p2;
    return tmp;
}
/********************   ExpNeq    ********************/
Exp make_ExpNeq(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ExpNeq!\n");
        exit(1);
    }
    tmp->kind = is_ExpNeq;
    tmp->u.expneq_.exp_1 = p1;
    tmp->u.expneq_.exp_2 = p2;
    return tmp;
}/********************   ListExp    ********************/
ListExp make_ListExp(Exp p1, ListExp p2)
{
    ListExp tmp = (ListExp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListExp!\n");
        exit(1);
    }
    tmp->exp_ = p1;
    tmp->listexp_ = p2;
    return tmp;
}/********************   AssertionTypeEqual    ********************/
Assertion make_AssertionTypeEqual(Id p1, Type p2)
{
    Assertion tmp = (Assertion) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating AssertionTypeEqual!\n");
        exit(1);
    }
    tmp->kind = is_AssertionTypeEqual;
    tmp->u.assertiontypeequal_.id_ = p1;
    tmp->u.assertiontypeequal_.type_ = p2;
    return tmp;
}/********************   TypeInitDouble    ********************/
Type make_TypeInitDouble(CoreType p1, Double p2)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TypeInitDouble!\n");
        exit(1);
    }
    tmp->kind = is_TypeInitDouble;
    tmp->u.typeinitdouble_.coretype_ = p1;
    tmp->u.typeinitdouble_.double_ = p2;
    return tmp;
}
/********************   TypeInitInt    ********************/
Type make_TypeInitInt(CoreType p1, Integer p2)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TypeInitInt!\n");
        exit(1);
    }
    tmp->kind = is_TypeInitInt;
    tmp->u.typeinitint_.coretype_ = p1;
    tmp->u.typeinitint_.integer_ = p2;
    return tmp;
}
/********************   TypeExponential    ********************/
Type make_TypeExponential(CoreType p1)
{
    Type tmp = (Type) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating TypeExponential!\n");
        exit(1);
    }
    tmp->kind = is_TypeExponential;
    tmp->u.typeexponential_.coretype_ = p1;
    return tmp;
}/********************   CoreTypeBase    ********************/
CoreType make_CoreTypeBase(BaseType p1)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeBase!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeBase;
    tmp->u.coretypebase_.basetype_ = p1;
    return tmp;
}
/********************   CoreTypeMulPair    ********************/
CoreType make_CoreTypeMulPair(Type p1, Type p2)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeMulPair!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeMulPair;
    tmp->u.coretypemulpair_.type_1 = p1;
    tmp->u.coretypemulpair_.type_2 = p2;
    return tmp;
}
/********************   CoreTypeSum    ********************/
CoreType make_CoreTypeSum(Type p1, Type p2)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeSum!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeSum;
    tmp->u.coretypesum_.type_1 = p1;
    tmp->u.coretypesum_.type_2 = p2;
    return tmp;
}
/********************   CoreTypeList    ********************/
CoreType make_CoreTypeList(Type p1)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeList!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeList;
    tmp->u.coretypelist_.type_ = p1;
    return tmp;
}
/********************   CoreTypeNamed    ********************/
CoreType make_CoreTypeNamed(Ident p1, Generics p2)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeNamed!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeNamed;
    tmp->u.coretypenamed_.ident_ = p1;
    tmp->u.coretypenamed_.generics_ = p2;
    return tmp;
}
/********************   CoreTypeFunction    ********************/
CoreType make_CoreTypeFunction(ListType p1, Type p2)
{
    CoreType tmp = (CoreType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating CoreTypeFunction!\n");
        exit(1);
    }
    tmp->kind = is_CoreTypeFunction;
    tmp->u.coretypefunction_.listtype_ = p1;
    tmp->u.coretypefunction_.type_ = p2;
    return tmp;
}/********************   GenericsNone    ********************/
Generics make_GenericsNone()
{
    Generics tmp = (Generics) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating GenericsNone!\n");
        exit(1);
    }
    tmp->kind = is_GenericsNone;
    return tmp;
}
/********************   GenericsType    ********************/
Generics make_GenericsType(Type p1)
{
    Generics tmp = (Generics) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating GenericsType!\n");
        exit(1);
    }
    tmp->kind = is_GenericsType;
    tmp->u.genericstype_.type_ = p1;
    return tmp;
}/********************   ListType    ********************/
ListType make_ListType(Type p1, ListType p2)
{
    ListType tmp = (ListType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListType!\n");
        exit(1);
    }
    tmp->type_ = p1;
    tmp->listtype_ = p2;
    return tmp;
}/********************   BaseType_Int    ********************/
BaseType make_BaseType_Int()
{
    BaseType tmp = (BaseType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BaseType_Int!\n");
        exit(1);
    }
    tmp->kind = is_BaseType_Int;
    return tmp;
}
/********************   BaseType_Unit    ********************/
BaseType make_BaseType_Unit()
{
    BaseType tmp = (BaseType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BaseType_Unit!\n");
        exit(1);
    }
    tmp->kind = is_BaseType_Unit;
    return tmp;
}
/********************   BaseTypeDouble    ********************/
BaseType make_BaseTypeDouble()
{
    BaseType tmp = (BaseType) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating BaseTypeDouble!\n");
        exit(1);
    }
    tmp->kind = is_BaseTypeDouble;
    return tmp;
}
